@startuml
title US722\nAs a Power User [or Administrator], I want to know the total metered energy consumption of a grid\nin agiven time interval,\ni.e. the sum of the energy consumption of all energy-metered rooms in the grid in the interval.
actor PowerUser
PowerUser -> EnergyConsumptionUI: runUS722
ref over EnergyConsumptionUI
selectGrid
end ref
ref over EnergyConsumptionUI
getInputStartDate
end ref
ref over EnergyConsumptionUI
getInputEndDate
end ref
EnergyConsumptionUI -> EnergyConsumptionController: getGridConsumptionInInterval (grid, startDate, endDate)
EnergyConsumptionController -> Grid: getConsumptionInInterval (startDate, endDate)
Grid -> RoomList: getConsumptionInInterval (startDate, endDate)
loop get consumption for each room
RoomList -> DeviceList: getConsumptionInInterval (startDate, endDate)
loop get consumption for each device in interval
DeviceList -> Device: getConsumptionInInterval (startDate, endDate)
end
DeviceList --> Grid: return sum
Grid --> EnergyConsumptionUI: return consumptionInInterval
EnergyConsumptionUI -> PowerUser: display total consumption in given interval
@enduml