@startuml

title US 101 - As an Administrator, I want to configure the location of the house.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana
skinparam titleFontSize 10


skinparam class {
  BorderColor indianred
  BackgroundColor indianred
  BackgroundColor ivory
   roundcorner 10
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
   FontSize 12
}

class GASettingsWebController
class HouseRepository
class HouseMapper
class HouseCrudRepository
class AddressAndLocalDTO
class HouseWithoutGridsDTO

GASettingsWebController -- HouseRepository : >
GASettingsWebController -- HouseWithoutGridsDTO : >

HouseRepository -- HouseCrudRepository : >
HouseRepository -- House : >
HouseRepository -- HouseMapper : >
HouseMapper -- HouseWithoutGridsDTO : >

HouseWithoutGridsDTO -- AddressAndLocalDTO : >

AddressAndLocalDTO -- AddressDTO : >
AddressAndLocalDTO -- LocalDTO : >

class GASettingsWebController {
-configureHouseLocation(@RequestBody AddressAndLocalDTO)
}


class HouseMapper{
- objectToWithoutGridsDTO(house)
- dtoWithoutGridsToObject(houseWithoutGridsDTO)
}

class HouseRepository {
- getHouseWithoutGridsDTO()
- updateHouseDTOWithoutGrids(HouseWithoutGridsDTO)
}

class HouseWithoutGridsDTO {
- setAddressAndLocalToDTOWithoutGrids()
}

class AddressAndLocalDTO{
setAddress(addressDTO)
setLocal(localDTO)
}

class AddressDTO{
}

class LocalDTO{
}

class HouseCrudRepository{
- findAll()
- save(House)
}

@enduml