@startuml

title US 101 - As an Administrator, I want to configure the location of the house.

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


class GASettingsWebController
class GeographicAreaRepository
class GeographicAreaMapper
class GeographicAreaCrudRepository
class GeographicAreaDTO
class GeographicArea

GASettingsWebController -- GeographicAreaRepository : >
GASettingsWebController -- GeographicAreaDTO : >

GeographicAreaRepository -- GeographicAreaCrudRepository : >
GeographicAreaRepository -- GeographicArea : >
GeographicAreaRepository -- GeographicAreaMapper : >
GeographicAreaMapper -- GeographicAreaDTO : >



class GASettingsWebController {
-createGeoArea(@RequestBody GeographicAreaDTO)
}

class GeographicAreaMapper{
- dtoToObject(GeographicAreaDTO)
}

class GeographicAreaRepository {
- addAndPersistDTO(GeographicAreaDTO)
}


class GeographicAreaCrudRepository{
- save(House)
}

@enduml