@startuml

title US 101 - As an Administrator, I want to configure the location of the house.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana
skinparam titleFontSize 10


skinparam class {
  BorderColor indianred
  BackgroundColor indianred
  BackgroundColor ivory
   roundcorner 10
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
   FontSize 12
}

class GASettingsWebController
class GeographicAreaRepository
class GeographicAreaMapper
class GeographicAreaCrudRepository
class GeographicAreaDTO
class GeographicArea

GASettingsWebController -- GeographicAreaRepository : >
GASettingsWebController -- GeographicAreaDTO : >

GeographicAreaRepository -- GeographicAreaCrudRepository : >
GeographicAreaRepository -- GeographicArea : >
GeographicAreaRepository -- GeographicAreaMapper : >
GeographicAreaMapper -- GeographicAreaDTO : >



class GASettingsWebController {
-createGeoArea(@RequestBody GeographicAreaDTO)
}

class GeographicAreaMapper{
- dtoToObject(GeographicAreaDTO)
}

class GeographicAreaRepository {
- addAndPersistDTO(GeographicAreaDTO)
}


class GeographicAreaCrudRepository{
- save(House)
}

@enduml