@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US003 - As an Administrator, I want to create a new Geographic Area

actor "Http Client"
activate "Http Client"
"Http Client" -> "SpringResolver":  Post ".../geographic_area_settings/areas"
activate "SpringResolver"
"SpringResolver"->"GASettingsWebController": createGeographicArea(GeographicAreaDTO)
deactivate "SpringResolver"
activate "GASettingsWebController"
"GASettingsWebController" -> "GeographicAreaRepository": addAndPersistDTO(GeographicAreaDTO)
activate "GeographicAreaRepository"
"GeographicAreaRepository" -> "GeographicAreaMapper": GeographicArea = dtoToObject(GeographicAreaDTO)
activate "GeographicAreaMapper"
"GeographicAreaMapper" --> "GeographicAreaRepository": return GeographicArea
deactivate "GeographicAreaMapper"
"GeographicAreaRepository" -> "GeographicAreaCrudRepository": save GeographicArea
alt if geographic area is Added
"GeographicAreaRepository" -->  "GASettingsWebController": return true
"GASettingsWebController" --> "Http Client": new ResponseEntity<>(success message, HttpStatus.CREATED)
else if geographic area is NOT Added
"GeographicAreaRepository" -->  "GASettingsWebController": return false
"GASettingsWebController" --> "Http Client": new ResponseEntity<>(failed message, HttpStatus.CONFLICT)
else if geographic area is NOT Added due to null parameters
"GeographicAreaRepository" -->  "GASettingsWebController": return false
deactivate "GeographicAreaRepository"
"GASettingsWebController" --> "Http Client": new ResponseEntity<>(failed message, HttpStatus.BAD_REQUEST)
deactivate "GASettingsWebController"
deactivate "Http Client"
end

@enduml