@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}



title JSONFileReading
-> ReadingsReaderJSON: readFile(filePath)
activate ReadingsReaderJSON



ReadingsReaderJSON -> File: file = new File(filePath);

create ":objectMapper"
ReadingsReaderJSON -> ":objectMapper": new XmlMapper();
ReadingsReaderJSON -> ":objectMapper": objectMapper.readValue(file, ReadingDTOLWrapperList.class);
":objectMapper" -> ReadingsReaderJSON: ReadingDTOWrapperList

ReadingsReaderJSON -> ReadingDTOWrapperList: List<ReadingDTOWrapper> = getReadingDTOWrapperList();

ReadingsReaderJSON -> Adapter: readingDTOWrapperConversion(List<ReadingDTOWrapper>)
Adapter -> ReadingsReaderJSON: List<ReadingDTO>

<- ReadingsReaderJSON: List<ReadingDTO>
deactivate "ReadingsReaderJSON"

@enduml