@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}



title CSVFileReading
-> ReadingsReaderCSV: readFile(filePath)
activate ReadingsReaderCSV


ReadingsReaderCSV -> CsvSchema: csvSchema = CsvSchema.emptySchema().withHeader();

ReadingsReaderCSV -> File: csvFile = new File(filePath);

create ":csvMapper"
ReadingsReaderCSV -> ":csvMapper": new CsvMapper();
ReadingsReaderCSV -> ":csvMapper": csvMapper.readerFor(ReadingDTOWrapper.class).with(csvSchema).readValues(csvFile);
":csvMapper" -> ReadingsReaderCSV: List<ReadingDTOWrapper>

ReadingsReaderCSV -> Adapter: readingDTOWrapperConversion(readingDTOWrappers)
Adapter -> ReadingsReaderCSV: List<ReadingDTO>

<- ReadingsReaderCSV: List<ReadingDTO>
deactivate "ReadingsReaderCSV"

@enduml