@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

-> GeographicAreaService: getReadingsBelowCategoryILimit(readingValues, house)
activate GeographicAreaService
GeographicAreaService -> GeographicAreaService: List<Reading> finalreadings = new ArrayList<>();
loop for each Reading
GeographicAreaService -> GeographicAreaService: double temperature = getGeographicAreaAverageTemperature(ReadingDate, GeographicArea)
GeographicAreaService -> GeographicAreaService: categoryICalculusTemperaturesLowerThanAverage(Reading, temperature)
alt if reading temperature value is lower than "0.33 * areaTemperature + 18.8 - 2"
GeographicAreaService -> GeographicAreaService: finalreadings.add(reading)
deactivate GeographicAreaService


end

end



@enduml
