@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

-> RoomService: getReadingsInInterval(StartingDate,EndingDate,Room)
title REF Readings in Interval
activate RoomService
RoomService -> RoomRepository: List <RoomSensor> = findAll()
loop for each Room
RoomService -> Room: List<RoomSensor> temperatureSensors = getRoomSensorsOfGivenType("temperature");
loop for each Reading
RoomService -> ReadingUtils: isReadingDateBetweenTwoDates(readingDate, initialDate, finalDate)
alt if readingDate is contained between initial Date and final Date
RoomService -> RoomService: readingValues.add(reading)
deactivate RoomService
end

end

end



@enduml

