@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title REF Date Interval Selection

actor User

activate ":RoomMonitoringUI"
":RoomMonitoringUI" -> ":RoomMonitoringUI": getStartDate()
":RoomMonitoringUI" -> ":InputUtils": getInputYearMonthDay()
activate ":InputUtils"
":InputUtils" --> User: request year
User -> ":InputUtils": insert year
":InputUtils" --> User: request month
User -> ":InputUtils": insert month
":InputUtils" --> User: request day
User -> ":InputUtils": insert day
":InputUtils" -> ":InputUtils": createDate(year, month, day)
":InputUtils" --> ":RoomMonitoringUI": return Date
deactivate ":InputUtils"
deactivate User
@enduml