@startuml

title US752 \n  I want to estimate the total energy used in heating water in a given day

autonumber


actor User
activate MainUI
User -> MainUI: request energy consumption\n on heating water

MainUI -> EnergyConsumptionUI:  energyConsumptionUI.run(house)

activate EnergyConsumptionUI
EnergyConsumptionUI -> EnergyConsumptionUI: run US752(house)

EnergyConsumptionUI -> EnergyConsumptionController: getWaterHeaterDeviceList(house)
activate EnergyConsumptionController
EnergyConsumptionController -> House: getHouseDevicesOfGivenType(deviceType)
activate House
House --> EnergyConsumptionController: return Water Heaters List
deactivate House
EnergyConsumptionController --> EnergyConsumptionUI: return Water Heaters List
deactivate EnergyConsumptionController

loop all house water heaters
    EnergyConsumptionUI --> User: request cold water temperature
        activate EnergyConsumptionUI
    User --> EnergyConsumptionUI: cold water temperature
    EnergyConsumptionUI -> EnergyConsumptionUI: set coldWaterTemp(double)
    EnergyConsumptionUI --> User: request volume of water to heat
    User --> EnergyConsumptionUI: volume of water to heat
    EnergyConsumptionUI -> EnergyConsumptionUI: set VolumeOfWaterToHeat(double)
    EnergyConsumptionUI -> EnergyConsumptionController: configureHeater(Device, double, double)
    participant Room
        deactivate EnergyConsumptionUI
    EnergyConsumptionController -> Device: setAttributeValue(String, double)
end

EnergyConsumptionUI -> EnergyConsumptionController: getDailyHouseConsumptionWaterHeater(house)
activate EnergyConsumptionController
EnergyConsumptionController -> House: getDailyHouseConsumptionPerType(DeviceType)
activate House
House -> Room: getDailyRoomConsumptionPerType(DeviceType)
activate Room
Room -> Device: getDailyEstimateConsumption()
activate Device
Device --> Room: return dailyEstimateConsumption
deactivate Device
Room --> House: return dailyRoomConsumption
deactivate Room
House --> EnergyConsumptionController: return dailyHouseConsumptionPerType
deactivate House
EnergyConsumptionController --> EnergyConsumptionUI: return dailyHouseConsumptionOnWaterHeaters
deactivate EnergyConsumptionController
EnergyConsumptionUI -> EnergyConsumptionUI: Build result string
EnergyConsumptionUI -> User: Display result string
deactivate EnergyConsumptionUI
deactivate MainUI
@enduml