@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title Get Geographic Area By Sensor ID From Repository
-> GeographicAreaService: getGeographicAreaContainingSensorWithGivenId\n(String sensorID)
activate GeographicAreaService
GeographicAreaService -> GeographicAreaRepository: List <GeographicArea> = findAll(String sensorID)
loop for each Geographic Area
GeographicAreaService -> GeographicArea: List<AreaSensor> areaSensors = getAreaSensors()
loop for each AreaSensor
alt if AreaSensorID matches given SensorID
<- GeographicAreaService: GeographicArea
deactivate GeographicAreaService
end
end
end



@enduml

