@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	backgroundColor Snow
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor snow
}

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 011 - As as Administrator I want to remove a sensor so that it will no longer be used.

actor "Admin"
activate "Admin"
"Admin" -> "Http Client": Remove Sensor From Area
activate "Http Client"
"Http Client" -> "SpringResolver": delete (".../areas/{id}/sensors/{id2}")
activate "SpringResolver"
"SpringResolver" -> "SensorSettingsWebController":  removeAreaSensor(Long areaID, String sensorID)
activate "SensorSettingsWebController"
"SensorSettingsWebController" -> "GeographicAreaRepository": getDTOById(Long areaID)
activate "GeographicAreaRepository"
"GeographicAreaRepository" --> "SensorSettingsWebController": return GeographicAreaDTO
deactivate "GeographicAreaRepository"
"SensorSettingsWebController" -> "GeographicAreaRepository": removeSensorDTO(GeographicAreaDTO geoAreaDTO, String sensorID)
activate "GeographicAreaRepository"
"GeographicAreaRepository" --> "SensorSettingsWebController": return true
deactivate "GeographicAreaRepository"
"SensorSettingsWebController" -> "GeographicAreaRepository": updateAreaDTO(GeographicAreaDTO)
activate "GeographicAreaRepository"
"GeographicAreaRepository" -> "GeographicAreaMapper": dtoToObject(areaDTO)
activate "GeographicAreaMapper"
"GeographicAreaMapper" --> "GeographicAreaRepository": return GeographicArea
deactivate "GeographicAreaMapper"
"GeographicAreaRepository" --> "GeographicAreaRepository": save(area)
deactivate "GeographicAreaRepository"

alt if sensor is removed
"SensorSettingsWebController" -> "Admin": new ResponseEntity<>(success message, HttpStatus.OK)
else if sensor is not found
"SensorSettingsWebController" -> "Admin": new ResponseEntity<>(failed message, HttpStatus.NOT_FOUND)
deactivate "SensorSettingsWebController"
deactivate "SpringResolver"
deactivate "Http Client"
deactivate "Admin"
end

@enduml