@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title Add Readings To Room Sensors
GASettingsUI -> ReadingsController: addReadingsToRoomSensors\n(List<ReadingDTO> readingDTOs, \nString logPath)
activate ReadingsController
ReadingsController -> ReadingMapper: List<Reading> readings = \nreadingDTOsToReadings(readingDTOs)
ReadingsController -> RoomService: addReadingsToRoomSensors\n(List<ReadingDTO> readingDTOs,\n String logPath)
activate RoomService

RoomService -> LogUtils: Logger logger = getLogger\n("areaReadingsLogger", logPath, Level.FINE)
RoomService -> ReadingUtils: List<String> sensorIDs = getSensorIDs(readings)


loop for each sensorID
RoomService -> ReadingUtils: List<Reading> subArray = getReadingsBySensorID(sensorID, readings)

RoomService -> RoomService: addedReadings = addRoomReadings\n(sensorID, subArray, logger)
ref over RoomService
Add Room Readings
end ref
end

RoomService -> ReadingsController: int addedReadings
ReadingsController -> GASettingsUI: int addedReadings

deactivate ReadingsController

@enduml