@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US265 \n  As an Administrator, I want to import a list of sensor readings of the house sensors. \n Data from non-existing sensors or outside the valid sensor operation period shouldn’t be imported but registered in the application log.


actor Administrator
Administrator -> MainUI:run()
activate MainUI
MainUI -> HouseConfigurationUI: runUS265
activate HouseConfigurationUI
HouseConfigurationUI -> "HouseConfigurationController": readReadingListFromFile
activate HouseConfigurationController
HouseConfigurationController -> "Reader": importHouseSensorReadingService
activate Reader
Reader -> HouseConfigurationUI: Request File Path
HouseConfigurationUI -> Administrator: Request File Path
Administrator --> HouseConfigurationUI: Insert File Path
HouseConfigurationUI -> HouseConfigurationController: read(filePath)
HouseConfigurationController -> "Reader": read(filePath)
"Reader" --> HouseConfigurationController: return List<readingDTO>
activate HouseConfigurationController
HouseConfigurationController -> SensorRepository: findById(readingDTO.sensorID)
SensorRepository --> HouseConfigurationController: Optional<Sensor>
alt if Optional<Sensor>.isPresent
HouseConfigurationController -> ReadingMapper: dtoToObject(readingDTO)
return roomSensor
HouseConfigurationController -> ReadingRepository: save(Reading)
HouseConfigurationController -> HouseConfigurationController: counter++;
else if Optional<Sensor> is not present
ref over HouseConfigurationController
logFailedImport(ReadingDTO)
end
end
HouseConfigurationController --> HouseConfigurationUI: return counter

HouseConfigurationUI -> Administrator: Display feedback message.
@enduml