@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title Add Readings To Geographic Area Sensors
GASettingsUI -> ReadingsController: addReadingsToGeographicAreaSensors\n(List<ReadingDTO>)
activate ReadingsController
ReadingsController -> ReadingsController: Logger logger = getLogger(logPath);


loop for each ReadingDTO
alt if Reading is Added
ReadingsController -> SensorService: addAreaReadingToAreaSensor\n(sensorID, value, date, unit, logger);

ReadingsController -> ReadingsController: addedReadings++

end

end

ReadingsController -> GASettingsUI: int addedReadings
deactivate ReadingsController

@enduml