@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title GetInputFileLocation
actor Administrator
ReaderController -> InputHelperUI: getInputJsonXmlCsv()
activate InputHelperUI
create ":Scanner"
InputHelperUI -> ":Scanner": scanner = new Scanner()
activate ":Scanner"
":Scanner" -> Administrator: ask for file location
InputHelperUI -> ":Scanner": scanner.next()
deactivate ":Scanner"
Administrator -> InputHelperUI: file path

InputHelperUI -> InputHelperUI: pathIsValid(filePath)
InputHelperUI -> ReaderController: file path
deactivate InputHelperUI

@enduml