@startuml
autonumber
actor Admin
Admin -> MainUI: Get List Of\nSensors in a Room
MainUI -> RoomConfigurationUI: getInputRoom()
RoomConfigurationUI -> House: getRoomList()
House -> RoomList: getRoomList()
RoomList -> RoomList: isEmpty()
RoomList --> RoomConfigurationUI: return false
RoomConfigurationUI -> RoomConfigurationController: printRoomList()
RoomConfigurationController --> Admin: Display RoomList
Admin --> MainUI: Select Room
MainUI -> RoomConfigurationUI: displaySensorListUS250()
RoomConfigurationUI -> Room : getmRoomSensorList()
Room -> Room: isEmpty()
Room --> RoomConfigurationUI: return false
RoomConfigurationUI -> RoomConfigurationController: printSensorList()
RoomConfigurationController --> Admin: Display SensorList
@enduml