@startuml
title US015v2 \n REF XML file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


InputUtils -> ReaderController: readFileXMLAndAddAreas(filePath)
ReaderController -> ReaderXML: readFile(filePath)
ReaderXML --> ReaderController: return Document
ReaderController->ReaderController:NodeList = getElementsByTagName("geographical_area")
loop success
ReaderController->ReaderController:readGeographicAreasXML(Node node)
create "geoArea :GeographicArea"
ReaderController -->> "geoArea :GeographicArea": create
"geoArea :GeographicArea" --> ReaderController: return geoArea
end loop

loop success
ReaderController -> GeographicAreaList: add(geoArea)
return return true
end loop
ReaderController --> InputUtils: return int
@enduml