@startuml
title US015v2 \n REF XML file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


InputHelperUI -> ReaderController: readFileXMLAndAddAreas(filePath)
activate InputHelperUI
activate ReaderController
ReaderController -> ReaderXML: readFile(filePath)
activate ReaderXML
deactivate ReaderController

ReaderXML --> ReaderController: return Document
deactivate ReaderXML

activate ReaderController
ReaderController->ReaderController:NodeList = getElementsByTagName("geographical_area")
loop success
ReaderController->ReaderController:readGeographicAreasXML(Node node)
create "geoArea :GeographicArea"
ReaderController -->> "geoArea :GeographicArea": create
activate "geoArea :GeographicArea"
deactivate ReaderController

"geoArea :GeographicArea" --> ReaderController: return geoArea
deactivate "geoArea :GeographicArea"
activate ReaderController
end loop

loop success
ReaderController -> GeographicAreaList: add(geoArea)
deactivate ReaderController
activate GeographicAreaList

GeographicAreaList-->ReaderController: return true
deactivate GeographicAreaList

activate ReaderController

end loop
ReaderController --> InputHelperUI: return int
deactivate ReaderController

@enduml