@startuml
actor Administrator
Administrator -> HouseConfigurationUI: Import data from .json file
HouseConfigurationUI -> InputUtils: getInputPath();
ref over InputUtils
getInputPath();
end ref
HouseConfigurationUI -> HouseConfigurationController: readFile(filePath)
HouseConfigurationController -> JSONReader: readFile(filePath)
loop
JSONReader -> GeographicArea: create();
end loop
GeographicArea --> JSONReader: return GeographicArea[]
JSONReader -> HouseConfigurationController: return GeographicArea[]
loop
HouseConfigurationController -> GeographicAreaList: add(GeographicArea)
end loop
HouseConfigurationUI -> Administrator: display feedback message.
@enduml