@startuml

actor PowerUser

activate PowerUser
-> ":EnergyConsumptionUI": selectRoom
activate ":EnergyConsumptionUI"
":EnergyConsumptionUI" -> ":InputUtils": getInputRoom(:House)
deactivate ":EnergyConsumptionUI"
activate ":InputUtils"
":InputUtils" -> ":House": getRoomList()
activate ":House"
":House" -> ":RoomList": getRoomList()
activate ":RoomList"
":RoomList" --> ":InputUtils": return :RoomList
deactivate ":RoomList"
deactivate ":House"
":InputUtils" -> ":InputUtils": buildRoomListString()
":InputUtils" -> PowerUser: Get input
PowerUser -> ":InputUtils": selectRoomByIndex()
":InputUtils" -> ":House": getRoom()
activate ":House"
":House" -> ":RoomList": getRoom()
activate ":RoomList"
":RoomList" -> ":Room":getRoom()
activate ":Room"
<-- ":Room": return :Room
deactivate ":RoomList"
deactivate ":House"
deactivate ":Room"
deactivate PowerUser
@enduml