@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title Add Readings To Room Sensor (RoomService)
activate RoomService
RoomService -> RoomService: Room room =\n getRoomContainingSensorWithGivenId(sensorID)
RoomService -> Room: RoomSensor roomSensor = room.getRoomSensorByID(sensorID);
RoomService -> RoomService: int addedReadings =\n addReadingsToRoomSensor(roomSensor, readings, logger);
ref over RoomService
Add Readings To Room Sensor
end
RoomService -> RoomRepository: save(room)

deactivate RoomService


@enduml

