@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	backgroundColor Snow
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor snow
}

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 108 - As an Http Client I want to a list of all existing Rooms


"HouseConfigurationWebController" -> ":RoomRepository":  getAllRoomDTOs()
activate ":RoomRepository"
":RoomRepository" -> "RoomCrudRepository": List<Room> rooms = findAll()
loop for each Room in rooms
":RoomRepository" -> "RoomMapper": RoomDTO roomDTO = objectToDTO(room)
":RoomRepository" -> ":RoomRepository": List<RoomDTO> listOfRoomDTOs = new ArrayList<>()
":RoomRepository" -> ":RoomRepository": listOfRoomDTOs.add(roomDTO)
end
":RoomRepository" -> "HouseConfigurationWebController": listOfRoomDTOs
deactivate ":RoomRepository"
@enduml