@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	backgroundColor Snow
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor snow
}

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 108 - As an Http Client I want to a list of all existing Rooms

actor "Http Client"
activate "Http Client"
"Http Client" -> "HouseConfigurationWebController":  GET ".../houseSettings/houseRooms": getHouseRooms()
activate "HouseConfigurationWebController"
"HouseConfigurationWebController" -> ":RoomRepository": getAllRoomDTOs()
":RoomRepository" -> "HouseConfigurationWebController": List<RoomDTO> roomDTOs
"HouseConfigurationWebController" -> "Http Client":  new ResponseEntity<>(roomDTOs, HTTPStatus.OK)
deactivate "HouseConfigurationWebController"
deactivate "Http Client"
@enduml