@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US147 \n As an Administrator, As an Administrator, I want to attach a room to a house grid, so that the room’s power and energy consumption is included in that grid.
autonumber
actor "Administrator"
"Administrator" -> ":HTTP Client":  Input data to attach room to a grid
activate ":HTTP Client"
":HTTP Client" -> ":EnergyGridSettingsWebController":  attachRoomToGrid(roomDTO, gridId)
activate ":EnergyGridSettingsWebController"
alt success
":EnergyGridSettingsWebController" -> ":EnergyGridRepository": attachRoomToGrid(roomDTO, gridId)
activate ":EnergyGridRepository"
":EnergyGridRepository" ->> ":EnergyGridRepository": getById(id)
":EnergyGridRepository" -> ":RoomMapper": dtoToObject(roomDTO)
activate ":RoomMapper"
":RoomMapper" --> ":EnergyGridRepository" : return room
deactivate ":RoomMapper"
":EnergyGridRepository" -> ":EnergyGrid": addRoom(room)
activate ":EnergyGrid"
":EnergyGrid" --> ":EnergyGridRepository" : return true
deactivate ":EnergyGrid"
":EnergyGridRepository" -> ":EnergyGridRepository" : save(energyGrid)
":EnergyGridRepository" --> ":EnergyGridSettingsWebController": return true
deactivate ":EnergyGridRepository"
":EnergyGridSettingsWebController" --> ":HTTP Client": ResponseEntity<>(HttpStatus.OK)
deactivate ":EnergyGridSettingsWebController"
":HTTP Client" -->> "Administrator": ResponseEntity<Object>(HttpStatus.OK)
deactivate ":HTTP Client"
else if room already contained in grid
":EnergyGridRepository" --> ":HTTP Client": ResponseEntity<>(HttpStatus.CONFLICT)
":HTTP Client" -->> "Administrator": ResponseEntity<Object>(HttpStatus.CONFLICT)
else if grid isn't present
":EnergyGridRepository" --> ":HTTP Client": ResponseEntity<>(HttpStatus.NOT_FOUND)
":HTTP Client" -->> "Administrator": ResponseEntity<Object>(HttpStatus.NOT_FOUND)
else if room isn't present
":EnergyGridRepository" --> ":HTTP Client": ResponseEntity<>(HttpStatus.NOT_FOUND)
":HTTP Client" -->> "Administrator": ResponseEntity<Object>(HttpStatus.NOT_FOUND)
end
@enduml