@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US147 \n As an Administrator, As an Administrator, I want to attach a room to a house grid, so that the room’s power and energy consumption is included in that grid.  \n - Success Case -
autonumber
actor "Administrator"
"Administrator" -> ":HTTP Client":  Input data to attach room to a grid
activate ":HTTP Client"
":HTTP Client" -> ":EnergyGridSettingsWebController":  Request Post at ".../grids/{energyGridId}"
activate ":EnergyGridSettingsWebController"
":EnergyGridSettingsWebController" -> ":EnergyGridRepository": attachRoomToGrid(roomDTO, gridId)
activate ":EnergyGridRepository"
":EnergyGridRepository" ->> ":EnergyGrid": getById(id)
activate ":EnergyGrid"
":EnergyGrid" --> ":EnergyGridRepository": return energyGrid
deactivate ":EnergyGrid"
":EnergyGridRepository" -> ":RoomMapper": dtoToObject(roomDTO)
activate ":RoomMapper"
":RoomMapper" --> ":EnergyGridRepository" : return room
deactivate ":RoomMapper"
alt success
":EnergyGridRepository" -> ":EnergyGrid": addRoom(room)
activate ":EnergyGrid"
":EnergyGrid" --> ":EnergyGridRepository" : return true
deactivate ":EnergyGrid"
":EnergyGridRepository" -> ":EnergyGridCrudeRepo" : save(energyGrid)
":EnergyGridRepository" --> ":EnergyGridSettingsWebController": return true
deactivate ":EnergyGridRepository"
":EnergyGridSettingsWebController" --> ":HTTP Client": ResponseEntity<>(HttpStatus.OK)
deactivate ":EnergyGridSettingsWebController"
":HTTP Client" -->> "Administrator": Http Status: 200 - Ok
deactivate ":HTTP Client"
@enduml