@startuml

title US 149 As an Administrator, I want to detach a room from a house grid, \n so that the room’s power and energy  consumption  is  not  included  in  that  grid.  The  room’s characteristics are not changed.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor Snow
skinparam FontName quicksand
skinparam titleFontSize 10
skinparam roundcorner 10


skinparam class {
 BorderColor indianred
 BackgroundColor indianred
 BackgroundColor Snow
  roundcorner 10
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
  FontSize 12
}

class EnergyGridSettingsWebController
class EnergyGridRepository
class EnergyGrid
class EnergyGridCrudeRepo

EnergyGridSettingsWebController -- EnergyGridRepository : >
EnergyGridRepository -- EnergyGrid : >
EnergyGridRepository -- EnergyGridCrudeRepo : >

class EnergyGridSettingsWebController {
detachRoomFromGrid(@RequestBody String roomID, @PathVariable("energyGridId") String gridId)
}

class EnergyGridRepository{
removeRoomFromGrid(gridId, roomID)
}


class EnergyGrid {
getById(gridName)
removeRoom(roomID)
}

class EnergyGridCrudeRepo{
save(energyGrid)
findById(id)
}

@enduml