@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


title US605 \n  I want to get the current temperature in a room.

autonumber

actor "HTTP Client"


"HTTP Client" ->> ":SpringResolver":  GET ".../roomMonitoring/currentRoomTemperature" \n getCurrentRoomTemperature \n
activate "HTTP Client"
activate ":SpringResolver"
":SpringResolver" ->> ":RoomMonitoringControllerWeb": getCurrentRoomTemperature \n
deactivate ":SpringResolver"
activate ":RoomMonitoringControllerWeb"
":RoomMonitoringControllerWeb" ->> ":RoomRepository": getCurrentRoomTempByRoomId \n
activate ":RoomRepository"
":RoomRepository" ->> ":RoomCrudRepo": findByRoomName(roomId)
activate ":RoomCrudRepo"
":RoomCrudRepo" ->> ":RoomRepository": return Room
deactivate ":RoomCrudRepo"
":RoomRepository" ->> ":Room": getCurrentRoomTemperature
activate ":Room"
":Room" ->> ":Room": getRoomSensorsOfGivenType
":Room" ->> ":Room": getReadings(tempSensors)
":Room" ->> ":ReadingUtils": getMostRecentValue(sensorReadings)
activate ":ReadingUtils"
":ReadingUtils" ->> ":Room": return double
deactivate ":ReadingUtils"
":Room" ->> ":RoomRepository": return double
deactivate ":Room"
alt Sensor with Readings (SUCCESS)
":RoomRepository" ->> ":RoomMonitoringControllerWeb": return double

":RoomMonitoringControllerWeb" -->> "HTTP Client": return  new ResponseEntity<>(double, HttpStatus.SUCCESS)
else if Room or Sensor Non-existent or without Readings on the given date
":RoomRepository" -->> ":RoomMonitoringControllerWeb": return throw Exception
deactivate ":RoomRepository"
":RoomMonitoringControllerWeb" -->> "HTTP Client": return  new ResponseEntity<>(failed message, HttpStatus.BAD_REQUEST)
deactivate "HTTP Client"
deactivate ":RoomMonitoringControllerWeb"
end


@enduml