@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 105 - As an Administrator I want to add a new room to the house\n Add Room To Room Crud Repository

"HouseConfigurationWebController" -> "RoomHouseService":  addRoomToCrudRepository(Room roomToAdd)
activate "RoomHouseService"
"RoomHouseService" -> "RoomWebMapper": Room room = dtoToObject(RoomDTOMinimal)
"RoomHouseService" -> "HouseRepository": String houseID = getHouseID()
"RoomHouseService" -> ":Room": room.setHouseID(houseID)

"RoomHouseService" -> "RoomRepository": addRoomToCrudRepository(room)

alt if room is added
return true
alt if else room is NOT added
return false
deactivate "RoomHouseService"
end
end
@enduml