@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 105 - As an Administrator I want to add a new room to the house\n Add Room To Room Crud Repository
autonumber
"HouseConfigurationWebController" -> "RoomRepository":  addRoomToCrudRepository(Room roomToAdd)
activate "RoomRepository"
"RoomRepository" -> ":Room": String roomToAddID = roomToAdd.getID(RoomDTO)
"RoomRepository" -> ":RoomCrudRepository": List<Room> listOfRooms = getAllRooms()

loop for each Room in ListOfRooms
"RoomRepository" -> ":Room": String roomID = room.getID(RoomDTO)
alt if roomID.equals(roomToAddID)
"RoomRepository" -> "HouseConfigurationWebController": return false
alt if else
"RoomRepository" -> "HouseConfigurationWebController": return true
deactivate "RoomRepository"
end
end
end
@enduml