@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 105 - As an Administrator I want to add a new room to the house \n Get House ID from House Crud Repository
autonumber
"HouseConfigurationWebController" -> "HouseRepository":  getHouseID()
activate "HouseRepository"
"HouseRepository" -> ":Room": String roomToAddID = roomToAdd.getID(RoomDTO)
"HouseRepository" -> "HouseCrudRepository": List<House> houseList = findAll()
"HouseRepository" -> "HouseRepository": House = houseList.get(0)
"HouseRepository" -> ":House": String houseID = house.getID()

"HouseRepository" -> "HouseConfigurationWebController":  return String houseID
deactivate "HouseRepository"
@enduml