@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	backgroundColor Snow
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor snow
}

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 105 - As an Http Client I want to add a new room to the house

actor "Http Client"
activate "Http Client"
"Http Client" -> "HouseConfigurationWebController":  Post ".../houseSettings/room": createRoom(@RequestBody RoomDTO roomDTO)
activate "HouseConfigurationWebController"
"HouseConfigurationWebController" -> "RoomDTOWeb": roomDTO.isNameValid()
"HouseConfigurationWebController" -> "RoomDTOWeb": roomDTO.areDimensionsValid()

alt if room DTO is valid
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(success message, HttpStatus.CREATED)
else if room name is NOT valid
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(failed message, HttpStatus.BAD_REQUEST)
else if room size is NOT valid
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(failed message, HttpStatus.UNPROCESSABLE_ENTITY)
end

"HouseConfigurationWebController" -> "HouseRoomService": addRoomDTOWebToHouse(RoomDTOWeb)

alt if room is Added
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(success message, HttpStatus.CREATED)
else if room is NOT Added
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(failed message, HttpStatus.CONFLICT)
deactivate "HouseConfigurationWebController"
deactivate "Http Client"
end
@enduml