@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 105 - As an Administrator I want to add a new room to the house

actor "Administrator"
activate "Administrator"
"Administrator" -> "HouseConfigurationWebController":  Post ".../houseSettings/room": createRoom(RoomDTO)
activate "HouseConfigurationWebController"
"HouseConfigurationWebController" -> "RoomWebMapper": Room = dtoToObject(RoomDTO)
"HouseConfigurationWebController" -> ":HouseRepository": String houseID = getHouseID()
"HouseConfigurationWebController" -> "Room": room.setHouseID(String houseID)

"HouseConfigurationWebController" -> ":RoomRepository": addRoomToRepository(Room room)

alt if room is Added
"HouseConfigurationWebController" -> "Administrator": new ResponseEntity<>(success message, HttpStatus.OK)
else if room is NOT Added
"HouseConfigurationWebController" -> "Administrator": new ResponseEntity<>(failed message, HttpStatus.CONFLICT)
deactivate "HouseConfigurationWebController"
deactivate "Administrator"
end

@enduml