@startuml

title US 007 - As an Administrator, I want to add an existing geographical area to another one.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor Snow
skinparam FontName quicksand
skinparam titleFontSize 10
skinparam roundcorner 10


skinparam class {
  BorderColor indianred
  BackgroundColor indianred
  BackgroundColor Snow
   roundcorner 10
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
   FontSize 12
}

class GeographicAreaRepository
class GeographicArea
class GeographicAreaCrudRepository


GASettingsWebController -right- GeographicAreaRepository : >
GeographicAreaRepository -right- GeographicArea : >
GeographicAreaRepository -right- GeographicAreaCrudRepository : >
GeographicAreaCrudRepository -- GeographicArea : >



class GASettingsWebController {
GeographicAreaRepository;
addDaughterArea(long, long)
}

class GeographicAreaRepository{
GeographicAreaCrudRepo;
addDaughterArea(long, long)
}

class GeographicArea{
Long ID;
List<GeographicArea>;
getDaughterAreas()
addDaughterArea(GeographicArea)
contains(GeographicArea)

}

interface GeographicAreaCrudRepository {
findById(long)
get()
save(GeographicArea)
}

@enduml