@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	backgroundColor Snow
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor snow
}

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US007 - As an Administrator, I want to add an existing geographical area to another one.
autonumber
actor "Admin"
"Admin" ->> ":HTTPClient":  Input data to put daughter area on mother area
activate ":HTTPClient"
":HTTPClient" ->> ":SpringResolver": Put ("...areas/{idMother}")
activate ":SpringResolver"
":SpringResolver" ->> ":GASettingsWebController": addDaughterArea(Long idAreaDaughter, Long idAreaMother)
deactivate ":SpringResolver"
activate ":GASettingsWebController"
":GASettingsWebController" ->> ":GeographicAreaRepository": addDaughterArea(Long idAreaDaughter, Long idAreaMother)
alt geographic area added
activate ":GeographicAreaRepository"
":GeographicAreaRepository" ->> ":GeographicAreaCrudRepository": findByID(Long idAreaMother)
":GeographicAreaCrudRepository" -->> ":GeographicAreaRepository": return :geographicAreaMother
":GeographicAreaRepository" ->> ":GeographicAreaCrudRepository": findById(Long idAreaDaughter)
":GeographicAreaCrudRepository" -->> ":GeographicAreaRepository": return :geographicAreaMother
alt geographic area not found
":GeographicAreaCrudRepository" -->> ":GeographicAreaRepository": return false
create ":ResponseEntity"
":GASettingsWebController" ->> ":ResponseEntity": create(String body, HttpStatus.NOT_FOUND);
activate ":ResponseEntity"
":ResponseEntity" -->> ":HTTPClient": ResponseEntity
deactivate ":ResponseEntity"
end
":GeographicAreaRepository" ->> ":geographicAreaMother": contains(geographicAreaDaughter)
":geographicAreaMother" -->> ":GeographicAreaRepository": return false
alt geographic area already contained
":geographicAreaMother" -->> ":GeographicAreaRepository": return true
":GASettingsWebController" ->> ":ResponseEntity": create(String body, HttpStatus.CONFLICT);
activate ":ResponseEntity"
":ResponseEntity" -->> ":HTTPClient": ResponseEntity
deactivate ":ResponseEntity"
end
":GeographicAreaRepository" ->> ":geographicAreaMother": add(geographicAreaDaughter)
deactivate ":GeographicAreaRepository"

":GASettingsWebController" ->> ":ResponseEntity": create(String body, HttpStatus.OK);
activate ":ResponseEntity"
deactivate ":GASettingsWebController"
":ResponseEntity" -->> ":HTTPClient": ResponseEntity

deactivate ":ResponseEntity"
deactivate ":HTTPClient"
end


@enduml