@startuml
title US015v2 \n REF XML file.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


title US80v2 \n I want the data related to GeographicAreas, including sensors and their readings,\n to be persisted in a relational database. \n - AreaSensor Example -

autonumber

Controller -> ":AreaSensorService": add(AreaSensor)
activate Controller
deactivate Controller
activate ":AreaSensorService"
create ":AreaSensor"

":AreaSensorService" ->> ":AreaSensor": create(String, SensorType, Local, Long)
":AreaSensorService" -> "AreaSensorRepository": save(AreaSensor)
activate "AreaSensorRepository"
deactivate "AreaSensorRepository"
deactivate ":AreaSensorService"


@enduml