@startuml
title US80v1 and v2 Persistence Class Diagram

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana

skinparam class {
 	BorderColor indianred
 	BackgroundColor indianred
 	BackgroundColor ivory
    roundcorner 10
    ArrowFontName Verdana
    ArrowColor indianred
    ArrowFontColor darkslategrey
 }

GeographicArea"1" -- "1"Location : has >
GeographicArea"0.*" -- "1"AreaType : has >
AreaSensor -- GeographicArea : is in >
AreaSensor"0.*" -- "1"Location : has >
AreaSensor"0.*" -- "1"SensorType : has >
AreaSensor"1" -- "0.*"Reading : may have >

House"1" -- "1"Location : has >
House"1" -- "1"Address : has >
House"1" -- "0.*"Room : may have >
House"1" -- "0.*"EnergyGrid : may have >
Room -- EnergyGrid : is in >

HouseSensor -- Room : is in >
HouseSensor"0.*" -- "1"Location : has >
HouseSensor"0.*" -- "1"SensorType : has >
HouseSensor"1" -- "0.*"Reading : has >




class GeographicArea {
long ID
String name
AreaType
Location
double length
double width
String description
}

class Location{
double latitude
double longitude
double altitude
}

class AreaType {
long ID
String name
}

class AreaSensor {
String ID
String name
SensorType
Localization
Date
long geographicAreaID
boolean active
}

class SensorType {
long ID
String name
}

class HouseSensor {
String ID
String name
SensorType
Date
long roomID
boolean active
}

class Reading {
double value
Date
String unit
String sensorID
}

class House {
String ID
Address
Location
int gridMeteringPeriod
int deviceMeteringPeriod
}

class Address {
String street
String number
String zip
String town
String country
}

class Room {
String name
String description
int houseFloor
double width
double length
double height
long energyGridId
}

class EnergyGrid {
long ID
String name
double maxContractedPower
long houseID
}






@enduml