@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US250 - As an Administrator, I want to get a list of all sensors in a room, so that I can configure them.
autonumber
actor "HTTP Client"
"HTTP Client"  -> ":SpringResolver":  Request GET at ".../rooms/{id}/sensors"
":SpringResolver" -> ":RoomConfigurationWebController": retrieveAllSensors\n(@PathVariable String id)
activate ":SpringResolver"
activate ":RoomConfigurationWebController"
":RoomConfigurationWebController" -> ":RoomRepository": RoomDTO roomDTO = getRoomDTOByName(String name)
activate ":RoomRepository"
":RoomRepository" ->> "RoomCrudRepository": Room room = findById(id)
activate "RoomCrudRepository"
deactivate "RoomCrudRepository"
deactivate ":RoomRepository"
":RoomConfigurationWebController" -> ":RoomRepository": List<RoomSensorDTOMinimal> roomSensorDTOList = getSensorDTOMinimalistList()
":RoomConfigurationWebController" --> ":SpringResolver": ResponseEntity<>(HttpStatus.OK)
":SpringResolver" -->> "HTTP Client": Http Status: 200 - O.K
deactivate ":RoomConfigurationWebController"

@enduml