@startuml

title US147 \n As an Administrator, I want to have a list of existing rooms attached to a house grid, so that I can attach/detach rooms from it.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor Snow
skinparam FontName quicksand
skinparam titleFontSize 10
skinparam roundcorner 10


skinparam class {
 BorderColor indianred
 BackgroundColor indianred
 BackgroundColor Snow
  roundcorner 10
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
  FontSize 12
}


class EnergyGridSettingsWebController
class EnergyGridRepository
class EnergyGrid
class RoomWebMapper
class EnergyGridCrudeRepo

EnergyGridSettingsWebController -- EnergyGridRepository : >
EnergyGridRepository -- EnergyGrid : >
EnergyGridRepository -- RoomWebMapper : >
EnergyGridRepository -- EnergyGridCrudeRepo : >



class EnergyGridSettingsWebController {
getRoomsWebDtoInGrid(@PathVariable("energyGridId") String gridId)
}

class EnergyGridRepository{
getRoomsDtoWebInGrid(String gridId)
}

class RoomWebMapper{
objectsToDtosWeb(roomList)
}


class EnergyGrid {
getRoomList()
}

class EnergyGridCrudeRepo{
findByName(gridId)
}

@enduml