@startuml
title US100 \n  As an Administrator, I want to configure the house from a file containing basic house information, grids and rooms.

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 2
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName verdana
skinparam titleFontSize 10


skinparam class {
 	BorderColor indianred
 	BackgroundColor indianred
 	BackgroundColor ivory
    roundcorner 10
    ArrowFontName Verdana
    ArrowColor indianred
    ArrowFontColor darkslategrey
    FontSize 12
 }


MainUI -- HouseConfigurationUI : >
HouseConfigurationUI -- ReaderController : >
ReaderController -- ReaderJSONHouse : >
ReaderController -- HouseMapper : >
HouseMapper -- AddressMapper : >
HouseMapper -- RoomService : >
HouseMapper -- EnergyGridService : >
ReaderController -- RoomMapper : >
ReaderController -- EnergyGridMapper : >
EnergyGridMapper -- RoomService : >
ReaderController -- EnergyGrid : >
ReaderController -- HouseService : >
ReaderController -- House : >

class HouseConfigurationUI{
runUS100(mainHouse, houseService)
}

class ReaderController{
readJSONAndSetHouse(House house, String filePath)
}

class ReaderJSONHouse{
readFile(String filePath)
readHouseJSON(JSONObject jsonObject)
readRoomsJSON()
readGridsJSON()
addRoomToGrid(String roomName)
readAddressJSON(JSONObject address)
}

class HouseMapper{
dtoToObjectUS100(HouseDTO dtoToConvert)
}

class EnergyGridMapper{
dtoToObjectUS100(EnergyGridDTO dtoToConvert)
}

class AddressMapper{
dtoToObject(AddressDTO dtoToConvert)
}

class RoomMapper{
dtoToObjectUS100(RoomDTO dtoToConvert)
}

class EnergyGridService{
addGrid(EnergyGrid energyGridToAdd)
}

class EnergyGrid{
setHouseId(String houseId)
}

class RoomService{
add(Room room)
}

class HouseService{
saveHouse(House house)
saveEnergyGrid(EnergyGrid energyGrid)
saveRoom(Room room)
}

class House{
setAddress(Address address)
getAddress()
getId()
setRoomService(RoomService roomService)
setGridList(EnergyGridService energyGridService)
}


@enduml