@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
 
title US 109 - As an Administrator, I want to edit the configuration of an existing room, so that I can reconfigure it

"HouseConfigurationWebController" -> "RoomRepository":  configureRoom(RoomDTO roomDTO)

"RoomRepository" -> ":RoomCrudRepository": Room room = findByRoomName(roomDTO.getName())
alt if room is Present
"RoomRepository" -> ":Room": room.setHouseFloor(roomDTO.getFloor())
"RoomRepository" -> ":Room": room.setRoomWidth(roomDTO.getWidth())
"RoomRepository" -> ":Room": room.setRoomLength(roomDTO.getLength())
"RoomRepository" -> ":Room": room.setRoomHeight(roomDTO.getHeight())
"RoomRepository" -> ":RoomCrudRepository": save(room)
"RoomRepository" -> "HouseConfigurationWebController": return true
else if room NOT Present
"RoomRepository" -> "HouseConfigurationWebController": return false
end

@enduml