@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	backgroundColor Snow
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor snow
}

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }
title US 109 - As an Administrator, I want to edit the configuration of an existing room, so that I can reconfigure it

actor "Http Client"
"Http Client" -> "HouseConfigurationWebController":  PUT ".../houseSettings/room": configureRoom(@RequestBody RoomDTO roomDTO)
activate "Http Client"

activate "HouseConfigurationWebController"
"HouseConfigurationWebController" -> "RoomDTO": roomDTO.areDimensionsValid()

alt if room DTO is valid
"HouseConfigurationWebController" -> ":RoomRepository": configureRoom(roomDTO)

alt room is configured
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(RoomDTO, HttpStatus.OK)

else if room is NOT configured
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(RoomDTO, HttpStatus.NOT_FOUND)
end

else if room dimensions are NOT valid
"HouseConfigurationWebController" -> "Http Client": new ResponseEntity<>(failed message, HttpStatus.UNPROCESSABLE_ENTITY)
deactivate "HouseConfigurationWebController"
deactivate "Http Client"
end

@enduml