@startuml
actor User
User -> MainUI: Get Average Rainfall on House Area
MainUI -> HouseMonitoringUI: Get Average Rainfall on House Area
HouseMonitoringUI --> User: Request Geographic Area Name or Index from List
User -> MainUI: insert data (Geographic Area name)
MainUI -> HouseMonitoringUI: set data (Geographic Area name) or Select GeoArea from List
HouseMonitoringUI ->HouseMonitoringController: check if name/index is contained in list
HouseMonitoringController -> GeographicAreaList: check if name/index is contained in list
GeographicAreaList -> GeographicArea: match by name or by index
GeographicArea -> GeographicArea: validate data
GeographicArea --> HouseMonitoringUI: set data (Geographic Area)
HouseMonitoringUI --> User: Request House Name or Index from List
User -> MainUI: insert data (House name) or Select House
MainUI -> HouseMonitoringUI: set data (House name)
HouseMonitoringUI -> HouseMonitoringController: check if name/index is contained in list
HouseMonitoringController -> HouseList: check if name/index is contained in list
HouseList -> House: match by name or by index
House -> House: validate data
House --> HouseMonitoringUI: set data (House)
HouseMonitoringUI --> User: Request Date
User -> MainUI: insert data (Date(y-m-d))
MainUI -> HouseMonitoringUI: set data (Date(y-m-d))
HouseMonitoringUI -> HouseMonitoringController: getAVGDailyRainfallOnGivenPeriod
HouseMonitoringController -> GeographicArea: getAvgReadingsFromSensorTypeInGA
GeographicArea -> ReadingList: getAverageReadingsBetweenTwoDays
Sensor->ReadingList: getReadingList
ReadingList->Reading:getMostRecentValueOfReading
Reading-->User: Display Current Temperature
@enduml