@startuml
title US015v3 \n As an Administrator, I want to import geographical areas and sensors from a JSON or a XML file (using Jackson API).
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


actor Administrator
Administrator -> GASettingsUI: Import data from .json or .xml file
activate Administrator
activate GASettingsUI
GASettingsUI -> InputHelperUI: getInputPathJsonOrXML()
activate InputHelperUI

ref over InputHelperUI
getInputPathJsonOrXML()
end ref

InputHelperUI --> GASettingsUI: return filePath
deactivate InputHelperUI
GASettingsUI->ReaderController : readFileJSONGeoAreas(filePath)
deactivate GASettingsUI
activate ReaderController
ReaderController->GeographicAreaReaderJSON:readFile(filePath)
deactivate ReaderController
activate GeographicAreaReaderJSON
create " :ObjectMapper"
GeographicAreaReaderJSON ->> " :ObjectMapper": new

GeographicAreaReaderJSON->" :ObjectMapper": readValue(file, GeographicAreaDTOWrapperList.class)
deactivate GeographicAreaReaderJSON
activate " :ObjectMapper"

" :ObjectMapper"-->GeographicAreaReaderJSON: return GeographicAreaDTOWrapperList
deactivate " :ObjectMapper"

activate GeographicAreaReaderJSON
GeographicAreaReaderJSON-->ReaderController: return List<GeographicAreaDTO>
deactivate GeographicAreaReaderJSON
activate ReaderController
loop
ReaderController -> GeographicAreaMapper: dtoToObject(GeographicAreaDTO)
deactivate ReaderController
activate GeographicAreaMapper

GeographicAreaMapper-->ReaderController: return GeographicArea
deactivate GeographicAreaMapper

activate ReaderController

ReaderController->GeographicAreaList: add(GeographicArea)
ReaderController->geographicAreaRepository: save (GeographicArea)
end loop

ReaderController-->GASettingsUI: return int
deactivate ReaderController

activate GASettingsUI

GASettingsUI --> Administrator: display feedback message.
deactivate GASettingsUI

deactivate Administrator

@enduml