@startuml
actor Administrator
Administrator->MainUI: Import a list of sensors \n for the house rooms.
MainUI->HouseConfigurationUI: runUS260(sensorService, roomService)
ref over HouseConfigurationUI
getInputPath
end
HouseConfigurationUI-> HouseConfigurationController: readSensors(filePath)
HouseConfigurationController -> RoomRepository: isEmpty();
RoomRepository --> HouseConfigurationController: false
create ":JSONSensorsReader"
HouseConfigurationController -> ":JSONSensorsReader": importSensors(filepath)
":JSONSensorsReader" --> HouseConfigurationController: List<HouseSensorDTO>
loop over HouseConfigurationController
HouseConfigurationController -> RoomRepository: findById(houseSensorDTO.roomID)
return Optional<Room>
alt if Optional<Room>.isPresent
HouseConfigurationController -> SensorMapper: dtoToObject(housesSensorDTO)
return houseSensor
HouseConfigurationController -> SensorRepository: save(houseSensor)
HouseConfigurationController -> HouseConfigurationController: counter++;
else if Optional<Room> is not present
ref over HouseConfigurationController
logFailedImport(houseSensorDTO)
end
end
end
HouseConfigurationController --> HouseConfigurationUI: return counter

HouseConfigurationUI -> Administrator: Display feedback message.
@enduml