@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


title US600 \n  I want to get the current temperature in the house area.

autonumber

actor "HTTP Client"


"HTTP Client" ->> ":SpringResolver":  GET ".../houseMonitoring/currentHouseAreaTemperature" \n getCurrentHouseAreaTemperature \n
activate "HTTP Client"
activate ":SpringResolver"
":SpringResolver" ->> ":HouseMonitoringControllerWeb": getCurrentHouseAreaTemperature \n
deactivate ":SpringResolver"
activate ":HouseMonitoringControllerWeb"
":HouseMonitoringControllerWeb" ->> ":GeographicAreaHouseService": getHouseAreaTemperature \n
activate ":GeographicAreaHouseService"
":GeographicAreaHouseService" ->> ":GeographicAreaHouseService": getClosestAreaSensorOfGivenType(TEMPERATURE)

":GeographicAreaHouseService" ->> ":AreaSensor": getReadings
activate ":AreaSensor"
":AreaSensor" ->> ":GeographicAreaHouseService": return List<Reading>
deactivate ":AreaSensor"

":GeographicAreaHouseService" ->> ":ReadingUtils": getMostRecentReading(sensorReadings)
activate ":ReadingUtils"
":ReadingUtils" ->> ":GeographicAreaHouseService": return Reading
deactivate ":ReadingUtils"

alt AreaSensor with Readings (SUCCESS)
":GeographicAreaHouseService" -->> ":HouseMonitoringControllerWeb": return double

":HouseMonitoringControllerWeb" -->> "HTTP Client": return  new ResponseEntity<>(double, HttpStatus.SUCCESS)
else if AreaSensor Non-existent or without Readings on the given date
":GeographicAreaHouseService" -->> ":HouseMonitoringControllerWeb": return throw Exception
deactivate ":GeographicAreaHouseService"
":HouseMonitoringControllerWeb" -->> "HTTP Client": return  new ResponseEntity<>(failed message, HttpStatus.BAD_REQUEST)
deactivate "HTTP Client"
deactivate ":HouseMonitoringControllerWeb"
end


@enduml