@startuml
title US100 \n As an Administrator, I want to configure the house from a file containing basic house information, grids and rooms.
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  }

  autonumber

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor ivory
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}


actor Administrator
Administrator -> HouseConfigurationUI: Import House data from .json file
activate Administrator
activate HouseConfigurationUI
HouseConfigurationUI -> HouseConfigurationUI: runUS100\n(house,houseService)
HouseConfigurationUI --> Administrator: "Please insert the location of\n the file you want to import:"
Administrator -> HouseConfigurationUI: Input File Path
HouseConfigurationUI -> InputHelperUI: getInputPathJson(filePath)
activate InputHelperUI
InputHelperUI --> HouseConfigurationUI: return filePath
deactivate InputHelperUI
HouseConfigurationUI -> ReaderController: readJSONAndSetHouse\n(house,filePath)
activate ReaderController
ref over ReaderController: readJSONAndSetHouse\n(house,filePath)
ReaderController --> HouseConfigurationUI: return true
deactivate ReaderController
HouseConfigurationUI --> Administrator: Successful Feedback Message
deactivate HouseConfigurationUI
deactivate Administrator

@enduml