@startuml
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor snow
skinparam FontName quicksand

skinparam actor {
  BorderColor indianred
  backgroundColor Snow
  }

skinparam sequence {
  LifeLineBackgroundColor indianred
  ParticipantBackgroundColor snow
}

skinparam roundcorner 10

skinparam component {
  arrowThickness 1
  ArrowFontName Verdana
  ArrowColor indianred
  ArrowFontColor darkslategrey
}

title US 010 - As as As an Administrator, I want to deactivate a sensor in a geographical area, so that it will no longer be used. It can be reactivated later.

actor "Admin"
activate "Admin"
"Admin" -> "SensorSettingsWebController":  Put ".../areas/{id}/sensors/{id2}": deactivateAreaSensor(Long areaID, String sensorID)
activate "SensorSettingsWebController"
"SensorSettingsWebController" -> "GeographicAreaRepository": getDTOById(Long areaID)
activate "GeographicAreaRepository"
"GeographicAreaRepository" --> "SensorSettingsWebController": return GeographicAreaDTO
deactivate "GeographicAreaRepository"
"SensorSettingsWebController" -> "GeographicAreaDTO": getAreaSensorByID(idSensor)
activate "GeographicAreaDTO"
"GeographicAreaDTO" --> "SensorSettingsWebController": return AreaSensorDTO
deactivate "GeographicAreaDTO"
"SensorSettingsWebController" -> "GeographicAreaDTO": deactivateSensorDTO(geographicArea, areaSensorDTO)
activate "GeographicAreaDTO"
"GeographicAreaDTO" --> "SensorSettingsWebController": return true
deactivate "GeographicAreaDTO"
"SensorSettingsWebController" -> "GeographicAreaRepository": updateAreaDTO(GeographicAreaDTO)
activate "GeographicAreaRepository"
"GeographicAreaRepository" -> "GeographicAreaMapper": dtoToObject(areaDTO)
activate "GeographicAreaMapper"
"GeographicAreaMapper" --> "GeographicAreaRepository": return GeographicArea
deactivate "GeographicAreaMapper"
"GeographicAreaRepository" --> "GeographicAreaRepository": save(area)
deactivate "GeographicAreaRepository"

alt if sensor is deactivated
"SensorSettingsWebController" -> "Admin": new ResponseEntity<>(success message, HttpStatus.OK)
else if sensor is already deactivated
"SensorSettingsWebController" -> "Admin": new ResponseEntity<>(failed message, HttpStatus.CONFLICT)
deactivate "SensorSettingsWebController"
deactivate "Admin"
end



@enduml