@startuml

activate DeviceTypeConfig

-> DeviceTypeConfig: getDeviceTypeConfig()
DeviceTypeConfig -> Properties: props = new Properties()
activate Properties


alt try
DeviceTypeConfig -> FileInputStream: input = new FileInputStream("resources/devices.properties")
activate FileInputStream
deactivate FileInputStream

DeviceTypeConfig -> Properties: load(input)
ref over DeviceTypeConfig, Properties
Read Device Types
end ref
deactivate Properties

else catch
DeviceTypeConfig -> DeviceTypeConfig: IOException
end


<- DeviceTypeConfig: return deviceTypeConfig
deactivate DeviceTypeConfig

@enduml