@startuml

-> DeviceTypeConfig: getDeviceTypeConfig()
activate DeviceTypeConfig
activate Properties

DeviceTypeConfig -> Properties: String deviceTypes = getProperty("allDeviceTypes")
DeviceTypeConfig -> DeviceTypeConfig: slip deviceTypes to Array of keys

loop for each device key
DeviceTypeConfig -> Properties: value = get(key)
DeviceTypeConfig -> DeviceTypeConfig: deviceTypeConfig = add(value)
end
deactivate Properties
deactivate DeviceTypeConfig

<- DeviceTypeConfig: return deviceTypeConfig

@enduml