@startuml
title US70 - Part 2 \n Device Creation: device type selection process and device creation with device type loaded from configuration

autonumber

actor Admin
RoomConfigurationUI -> RoomConfigurationController: getInputDeviceTypeByList(house)
RoomConfigurationController -> House: getmDeviceTypeList()
House --> RoomConfigurationController: return DTList
RoomConfigurationController --> RoomConfigurationUI: return DTList
RoomConfigurationUI -> Admin: show DTList
Admin -> RoomConfigurationUI: select DeviceType
RoomConfigurationUI -> RoomConfigurationController: createDevice(deviceType)
RoomConfigurationController -> DeviceType: createDeviceType()
DeviceType -> DeviceSpecs: create()
DeviceType -> Device: create(deviceSpecs)
DeviceType --> RoomConfigurationController: return device
RoomConfigurationController --> RoomConfigurationUI:  return device
RoomConfigurationUI -> RoomConfigurationUI: continue configuring device\n(loop on attributes/add to room)

@endumlΩ