@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }

actor PowerUser
-> ":RoomConfigurationUI": selectDevice
activate ":RoomConfigurationUI"
":RoomConfigurationUI" -> ":InputUtils": getInputDevice(:Room)
activate ":InputUtils"
":InputUtils" -> ":Room": getDeviceList()
activate ":Room"
":Room" --> ":InputUtils": return :DeviceList
deactivate ":Room"
":InputUtils" -> ":InputUtils": buildDeviceListString()
":InputUtils" -> PowerUser: display available devices
PowerUser -> ":InputUtils":  select index of device
":InputUtils" -> ":Room": getDeviceByIndex(index)
activate ":Room"
":Room" -> ":DeviceList": getDeviceByIndex(index)
activate ":DeviceList"
":DeviceList" --> ":RoomConfigurationUI": return :Device
deactivate ":DeviceList"
deactivate ":Room"
deactivate ":RoomConfigurationUI"
deactivate ":InputUtils"
@enduml