@startuml

actor PowerUser

-> ":RoomConfigurationUI": selectDevice
activate ":RoomConfigurationUI"
":RoomConfigurationUI" -> ":InputUtils": getInputDevice(:Room)
activate ":InputUtils"
":InputUtils" -> ":Room": getDeviceList()
activate ":Room"
":Room" -> ":DeviceList": getDeviceList()
activate ":DeviceList"
":DeviceList" --> ":InputUtils": return :DeviceList
deactivate ":DeviceList"
deactivate ":Room"
":InputUtils" -> ":InputUtils": buildDeviceListString()
":InputUtils" -> PowerUser: display available devices
PowerUser -> ":InputUtils":  select index of device
":InputUtils" -> ":Room": getDeviceByIndex(index)
activate ":Room"
":Room" -> ":DeviceList": getDeviceByIndex(index)
activate ":DeviceList"
":DeviceList" --> ":RoomConfigurationUI": return :Device
deactivate ":DeviceList"
deactivate ":Room"
deactivate ":RoomConfigurationUI"
deactivate ":InputUtils"
@enduml