@startuml

skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 3
skinparam titleBorderColor indianred
skinparam titleBackgroundColor ivory
skinparam FontName quicksand

skinparam actor {
 	BorderColor indianred
 	}

 skinparam sequence {
 	LifeLineBackgroundColor indianred
 	ParticipantBackgroundColor ivory
 }

 skinparam roundcorner 10

 skinparam component {
   arrowThickness 1
   ArrowFontName Verdana
   ArrowColor indianred
   ArrowFontColor darkslategrey
 }



-> CSVReader: setCSVReadings(Sensor sensor, Date date, Double value)
activate CSVReader
CSVReader -->> Sensor: Date startingDate = sensor.getDateStartedFunctioning();
alt IF date.after(startingDate) OR date == startingDate

CSVReader -->> Reading: Reading reading = new Reading(value, date);
CSVReader -> Sensor: addReading(reading);


end



@enduml